import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="inter.className">
      <Header/>
        {children}
      </body>
    </html>
  );
}
